# Generated by Django 3.0.7 on 2020-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servant_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('server', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('servant_id', 'server')},
            },
        ),
    ]
